### ISSUE TITLE
Language Design

### ISSUE THREAD

**Issue by napen123** [MathosProject/Docs#3]
What would declaring a function in the language look like?

**Comment by artemlos** [comment]
I guess something like:

```
func(x,y) := x * y 
```

the above is a function that maps x,y->func, let's say int -> int -> int (Haskell notation)

note bene, an interesting feature would be the following:

```
func(3,y) := 3 * y 
```

this, however, is y->func, i.e. int-> int (in Haskell)

a great idea would be to enable the following:

```
diff func(3,y) := 3*y => 3
```
